const PRODUCTS = Object.freeze({
  "kit-4-calcas-dryfit": { name: "Kit com 3 Calças Comfort Tech Premium", price: 7990 },
  "kit-3-oversized": { name: "KIT 3 CAMISETA Masculina Oversized Lisa Classica Basica Manga Curta Verão - Pague 1 Leve 3", price: 5990 },
  "kit-3-polo-poliamida": { name: "Kit 3 Camiseta Masculina Polo Poliamida Tecnológica Premium - Pague 1 Leve 3", price: 6990 },
  "tenis-slip-on": { name: "Tênis Masculino Slip On Casual Confortável Leve Dia a Dia", price: 6990 },
  "jaqueta-sarja-forrada": { name: "Jaqueta Masculina Sarja Casaco Com Capuz E Bolsos Forrada", price: 8990 },
  "calca-jeans-kit-3": { name: "Calça Jeans Masculina slim com Elastano – Kit 3 Peças", price: 7990 },
  "moletom-paris": { name: "Conjunto Moletom Masculino Estampado Blusa e Calça Casaco Estampa Paris", price: 7990 },
  "cuecas-dogzurb": { name: "Kit 5 Cuecas Boxer Masculinas Minimalistas DOGZURB em Microfibra Premium", price: 4590 },
  "jogger-skinny": { name: "Kit 3 Calça Jogger Masculina Skinny original academia", price: 7990 },
  "tenis-academia": { name: "Tênis Masculino Academia Esportivo Leve Confortável Caminhada Corrida", price: 5490 },
  "jaqueta-sarja-kit-3": { name: "Jaqueta De Sarja Masculina Toda Forrada Por Dentro Com Capuz Removível", price: 7990 },
  "polo-old-money": { name: "kit 3 Camisas Polo Old Money Masculina Canelada texturizada premium", price: 6990 },
  "kit-body-splash-trio": { name: "KIT BODY SPLASH MASCULINO BARBARIUS+ ENIGMA +MIDTOWN 200ML - Pague 1 Leve 3", price: 6990 },
  "kit-body-splash-barbours": { name: "Kit 3 Body Splash Masculino Homme Desodorante Barbours 200ml", price: 6990 },
  "cuecas-dryfit": { name: "Kit 5 Cuecas Boxer Dryfit Respiravel Antiodor Masculino", price: 5490 },
  "bermuda-monster": { name: "Bermuda Short Compressao 2 em 1 dry fit - Modelo Monster - Pague 1 Leve 5", price: 6990 },
  "camisa-polo-ventura": { name: "Camisa Polo Ventura Masculina", price: 6990 },
  "camisa-polo-court": { name: "Camisa Polo Court", price: 6990 },
  "relogio-pagani": { name: "Relógio Automático Pagani Luxury", price: 12990 },
  "relogio-chronos": { name: "Relógio Chronos Poedagar", price: 9990 },
  "kit-short-linho": { name: "Kit 4 Short Masculino Linho Bermuda Confortavél Verão Praia Festa", price: 6990 },
  "camisa-linho-rout": { name: "Camisa Linho Rout Manga Curta", price: 7990 },
  "sapato-oxford": { name: "Sapato Oxford Couro Legítimo", price: 11990 },
  "porta-cartao": { name: "Porta-Cartão Slim Couro Premium", price: 3990 },
  "relogio-classic": { name: "Relógio Classic Silver Masculino", price: 8990 },
  "carteira-couro": { name: "Carteira Couro Legítimo Premium", price: 4990 },
  "oculos-aviador": { name: "Óculos Aviador Polarizado UV400", price: 5990 },
  "cinto-couro": { name: "Cinto Couro Reversível Dupla Face", price: 4990 },
  "mocassim": { name: "Mocassim Premium Camurça Masculino", price: 10990 },
  "sueter-tricot": { name: "Suéter Tricot Gola Redonda Masculino", price: 8990 },
  "camisa-tricot": { name: "Camisa Camiseta Estilosa Masculina Malha Tricot Texturizada", price: 7990 },
  "tech-daily": { name: "Camiseta Básica Tech Daily Insider", price: 4990 }
});

module.exports = { PRODUCTS };
